name: CrazyLogin
main: de.st_ddt.crazylogin.CrazyLogin
author: ST-DDT
#C*=needed core version
version: C6.2_4.7
softdepend: [PermissionsBukkit]
depend: [CrazyCore]
commands:
  login:
    description: Show information about player
    usage: /<command> <Player>
  logout:
    description: Show information about online player
    usage: /<command>
  register:
    description: Create/Change password
    usage: /<command> <new Password>
  crazylogin:
    description: Plugin Main Menu
    usage: /<command> password <new Password>
permissions:
  crazylogin.*:
    description: Access to all commands
    default: false
    children:
      crazylogin.admin: true
      crazylogin.mode: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.register: true
  crazyonline.admin:
    description: Allow changing passwords for other players
    default: op
    children: 
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.register: true
  crazylogin.register:
    description: Allow players to create a password. (for external registration)
    default: true
  crazylogin.warnloginfailure:
    description: Get informed if someone fails to login
    default: op
  crazylogin.warncommandexploits:
    description: Get informed if someone tries to execute a none whitelisted command.
    default: op
  crazylogin.warndatabase:
    description: Get informed if database connection fails
    default: op
  crazylogin.warnalgorithm:
    description: Get informed if no algorithm is set.
    default: op
  crazyonline.mode:
    description: Allow changing plugin mode
    default: op