name: CrazyLogin
main: de.st_ddt.crazylogin.CrazyLogin
author: ST-DDT
#C*=needed core version
version: C7.3_5.5
softdepend: [PermissionsBukkit]
depend: [CrazyCore]
commands:
  login:
    description: Show information about player
    usage: /<command> <Player>
  logout:
    description: Show information about online player
    usage: /<command>
  register:
    description: Create/Change password
    usage: /<command> <new Password>
  crazylogin:
    description: Plugin Main Menu
    usage: /<command> password <new Password>
permissions:
  crazylogin.*:
    description: Access to all commands
    default: false
    children:
      crazylogin.admin: true
      crazylogin.mode: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.register: true
      crazylogin.commands: true
      crazylogin.playerinfo: true
      crazylogin.playerinfo.self: true
      crazylogin.playerinfo.other: true
      crazylogin.playerinfo.extended: true
  crazylogin.admin:
    description: Allow changing passwords for other players
    default: op
    children: 
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.register: true
      crazylogin.commands: true
  crazylogin.register:
    description: Allow players to create a password. (for external registration)
    default: true
  crazylogin.warnloginfailure:
    description: Get informed if someone fails to login
    default: op
  crazylogin.warncommandexploits:
    description: Get informed if someone tries to execute a none whitelisted command.
    default: op
  crazylogin.warndatabase:
    description: Get informed if database connection fails
    default: op
  crazylogin.warnalgorithm:
    description: Get informed if no algorithm is set.
    default: op
  crazylogin.warnsession:
    description: Get informed if somebody tries to login from another location.
    default: op
  crazylogin.warndelete:
    description: Get informed if old accounts are deleted (via admincommands)
    default: op
  crazylogin.delete:
    description: Allow deleting old accounts.
    default: op
    children:
      crazylogin.warndelete: true
  crazylogin.mode:
    description: Allow changing plugin mode
    default: op
  crazylogin.commands:
    description: Allow viewing and editing command whitelist.
    default: op
  crazylogin.playerinfo:
    description: Allow viewing playerinfo.
    default: op
    children:
      crazylogin.playerinfo.self: true
      crazylogin.playerinfo.other: true
      crazylogin.playerinfo.extended: true
  crazylogin.playerinfo.self:
    description: Allow viewing own playerinfo.
    default: true
  crazylogin.playerinfo.other:
    description: Allow viewing playerinfo for other players.
    default: op
  crazylogin.playerinfo.extended:
    description: Show link to detailed playerinfo.
    default: op