name: CrazyLogin
main: de.st_ddt.crazylogin.CrazyLogin
author: ST-DDT
version: 7.16.1
website: http://dev.bukkit.org/server-mods/crazylogin/
# requires CrazyCore v10.7.1 or later
depend: [CrazyCore]
description: >
            CrazyLogin protect your server with passwords and many usefully features.
commands:
  login:
    description: Login using a password
    usage: /<command> <Password...>
    aliases: [l]
  loginonce:
    description: Login using a password and enable auto logout
    usage: /<command> <Password...>
    aliases: [l1,lonce]
  adminlogin:
    description: Login using an admin account and enable auto logout
    usage: /<command> <Admin> <AdminPassword...>
  tokenlogin:
    description: Login using a token and enable auto logout
    usage: /<command> <Token>
  autologout:
    description: Enable auto logout
    usage: /<command>
  logout:
    description: Logout and leave server
    usage: /<command>
  register:
    description: Create/Change password
    usage: /<command> <new Password>
    aliases: [changepw,chgpw,changepassword]
  crazylogin:
    description: Plugin Main Menu
    usage: /<command> password <new Password>
    aliases: [cl,clogin]
permissions:
  crazylogin.*:
    description: Access to all commands
    default: false
    children:
      crazycore.protectedplayer: true
      crazylogin.admin: true
      crazylogin.mode: true
      crazylogin.mode.*: true
      crazylogin.saveloginlocation: true
      crazylogin.ensureregistration: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.bypasshidePlayer: true
      crazylogin.register.command: true
      crazylogin.register.channel: true
      crazylogin.login.command: true
      crazylogin.login.channel: true
      crazylogin.adminlogin: true
      crazylogin.tokenlogin: true
      crazylogin.requirepassword: true
      crazylogin.logout.command: true
      crazylogin.logout.channel: true
      crazylogin.commands: true
      crazylogin.dropolddata: true
      crazylogin.player.info: true
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
      crazylogin.player.create: true
      crazylogin.player.password: true
      crazylogin.player.password.protected: true
      crazylogin.player.delete: true
      crazylogin.player.delete.protected: true
      crazylogin.player.list: true
  crazylogin.admin:
    description: Allow changing account data for other players
    default: op
    children: 
      crazycore.protectedplayer: true
      crazylogin.mode: true
      crazylogin.mode.*: true
      crazylogin.saveloginlocation: true
      crazylogin.ensureregistration: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.bypasshidePlayer: true
      crazylogin.register.command: true
      crazylogin.register.channel: true
      crazylogin.login.command: true
      crazylogin.login.channel: true
      crazylogin.adminlogin: true
      crazylogin.tokenlogin: true
      crazylogin.requirepassword: true
      crazylogin.logout.command: true
      crazylogin.logout.channel: true
      crazylogin.commands: true
      crazylogin.dropolddata: true
      crazylogin.player.info: true
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
      crazylogin.player.create: true
      crazylogin.player.password: true
      crazylogin.player.password.protected: true
      crazylogin.player.delete: true
      crazylogin.player.delete.protected: true
      crazylogin.player.list: true
      crazylogin.player.detachip: true
      crazylogin.player.reverify: true
  crazylogin.ensureregistration:
    description: This player can always register an account.
    default: op
    children: 
      crazylogin.register.command: true
      crazylogin.register.channel: true
  crazylogin.register.command:
    description: Allow players to create a password via command.
    default: true
  crazylogin.register.channel:
    description: Allow players to create a password via pluginChannel.
    default: true
  crazylogin.login.command:
    description: Allow players to login via command.
    default: true
  crazylogin.login.channel:
    description: Allow players to login via pluginChannel.
    default: true
  crazylogin.adminlogin:
    description: Allow admins to login as another player.
    default: op
    children:
      crazylogin.requirepassword: true
  crazylogin.tokenlogin:
    description: Allow creations of tokens to login as another player.
    default: op
    children:
      crazylogin.requirepassword: true
  crazylogin.requirepassword: 
    description: Force this player to create a password.
    default: op
  crazylogin.blockadminlogin:
    description: Block admins logins to this account.
    default: false
  crazylogin.blocktokenlogin:
    description: Block token logins to this account.
    default: false
  crazylogin.logout.command:
    description: Allow players to logout via command.
    default: true
  crazylogin.logout.channel:
    description: Allow players to logout via pluginChannel.
    default: true
  crazylogin.warnloginfailure:
    description: Get informed if someone fails to login
    default: op
  crazylogin.warncommandexploits:
    description: Get informed if someone tries to execute a none whitelisted command.
    default: op
  crazylogin.warndatabase:
    description: Get informed if database connection fails
    default: op
  crazylogin.warnalgorithm:
    description: Get informed if no algorithm is set.
    default: op
  crazylogin.warndelete:
    description: Get informed if old accounts are deleted (via admincommands)
    default: op
  crazylogin.warnsession:
    description: Get informed if somebody tries to login from another location.
    default: op
  crazylogin.bypasshidePlayer:
    description: Show all players to this player even if they are hidden due to hidePlayer option.
    default: op
  crazylogin.mode:
    description: Allow accessing mode command
    default: op
  crazylogin.mode.*:
    description: Allow changing plugin all modes
    default: op
  crazylogin.saveloginlocation:
    description: Allow viewing and changing save login locations
    default: op
  crazylogin.commands:
    description: Allow viewing and editing command whitelist.
    default: op
  crazylogin.dropolddata:
    description: Allow deleting old accounts.
    default: op
    children:
      crazylogin.warndelete: true
  crazylogin.player.info:
    description: Allow viewing playerinfo.
    default: op
    children:
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
  crazylogin.player.info.self:
    description: Allow viewing own playerinfo.
    default: true
  crazylogin.player.info.other:
    description: Allow viewing playerinfo for other players.
    default: op
  crazylogin.player.create:
    description: Allow creating player data
    default: op
  crazylogin.player.password:
    description: Allow changing a player's password.
    default: op
  crazylogin.player.password.protect:
    description: Allow changing a protected player's password.
    default: op
    children:
      crazylogin.player.password: true
  crazylogin.player.delete:
    description: Allow deleting a player's account.
    default: op
  crazylogin.player.delete.protected:
    description: Allow deleting a protected player's account.
    default: op
    children:
      crazylogin.player.delete: true
  crazylogin.player.list:
    description: Allow viewing all players accounts.
    default: op
  crazylogin.player.detachip:
    description: Allow removing an IP from a player.
    default: op
  crazylogin.player.reverify:
    description: Allow forcing a player to login again.
    default: op